
# Site metadata
# ---------------------

title: WAVE Festival

author:
  name: WAVE Festival
  email: wavefestsound@gmail.com

description: >
  Women Amplify the Voice of Electroacoustic (WAVE) Music Festival

# Build settings
# ---------------------

remote_theme: jekyll/minima@bf9ef98

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: solarized-light

  nav_pages:
    - about.md
    - index.md
    - contact.md

  social_links:

  hide_site_feed_link: true

